server:
  port: 9000
  servlet:
    context-path: /api/app

spring:
  application:
    name: service-mode-app
  profiles:
    active: dev
knife4j:
  enable: true

---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.86.4:4307/word-center?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: admin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000
  redis:
    database: 0
    host: 101.34.86.4
    port: 6380
    timeout: 6000
    password: mode123
    lettuce:
      pool:
        min-idle: 10
        max-idle: 30
        max-active: 8
        max-wait: 60000
# 暴露的统计节点，可访问 http://localhost:8081/actuator/prometheus
management:
  server:
    port: 8081
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
      #base-path: "/study" # 这个注释会使得访问的节点变为 /study/prometheus

---
spring:
  profiles: prod

# 生产环境停用swg
knife4j:
  production: true