server:
  port: 9000
  servlet:
    context-path: /api/app

spring:
  application:
    name: service-mode-app
  profiles:
    active: dev
knife4j:
  enable: true

---
spring:
  profiles: dev
  #  datasource:
  #    driverClassName: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://101.34.86.4:4307/word-center?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
  #    username: admin
  #    password: 123456
  #    type: com.zaxxer.hikari.HikariDataSource
  #    hikari:
  #      minimum-idle: 10
  #      maximum-pool-size: 30
  #      auto-commit: true
  #      idle-timeout: 30000
  #      pool-name: HikariCP
  #      max-lifetime: 900000
  #      connection-timeout: 10000
  #      connection-test-query: SELECT 1
  #      validation-timeout: 1000
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      # 参考：SpringBootConfiguration 配置，配置的别名
      names: word-center,db-bj,db-sh,db-sz
      word-center:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://101.34.86.4:4307/word-center?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: admin
        password: 123456
      db-bj:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://101.34.86.4:4307/order_bj?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: admin
        password: 123456
      db-sh:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://101.34.86.4:4307/order_sh?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: admin
        password: 123456
      db-sz:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://101.34.86.4:4307/order_sz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: admin
        password: 123456
    sharding:
      default-data-source-name: word-center
      tables:
        t_order:
          # 行表达式标识符可以使用${...}或$->{...}，但前者与Spring本身的属性文件占位符冲突，因此在Spring环境中使用行表达式标识符建议使用$->{...}
          # 数据节点：多数据源如  db$->{0..1}.t_order_$->{0..2}  db-$->{['bj','sh','sz']}.t_order_$->{0..1}
          actual-data-nodes: db-$->{['bj','sh','sz']}.t_order_$->{0..1}
          database-strategy:   # 拆分库策略
            standard:
              sharding-column: zone    # 分片字段  standard 精确分片算法类名称，用于=和IN
              precise-algorithm-class-name: com.mode.technology.config.MyShardingDatabaseAlgorithm
          table-strategy:    # 拆分表策略
              inline:
                sharding-column: user_id    # 分片字段（分片键）
                algorithm-expression: t_order_$->{user_id % 2} # 分片算法表达式
          key-generator: # 自增列名称，缺省表示不使用自增主键生成器
            column: order_id
            type: SNOWFLAKE


  redis:
    database: 0
    host: 101.34.86.4
    port: 6380
    timeout: 6000
    password: mode123
    lettuce:
      pool:
        min-idle: 10
        max-idle: 30
        max-active: 8
        max-wait: 60000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# 暴露的统计节点，可访问 http://localhost:8081/actuator/prometheus
management:
  server:
    port: 8081
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
      #base-path: "/study" # 这个注释会使得访问的节点变为 /study/prometheus

---
spring:
  profiles: prod

# 生产环境停用swg
knife4j:
  production: true